---
title: "nextseq-variability"
author: "Kate Sheridan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(here)
library(ggpubr)

fastq <- here('rawdata', 'peco', 'fastq', 'miseq_nextseq')
datefield <- '20260404_'

```

# Read retention summary statistics

These files map where the reads went throughout the entire QC process

```{r load-in read retention}
# 2022 run miseq
retention_2022_miseq <- read_csv(here(fastq, 
                                   'miseq_2022_run2', 'fixed', 'qc_plots',
                                   '20260331_peco2022_miseq-library2_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2022) %>%
  mutate(seqmethod = 'miseq') %>%
  # remove tail of sample name
  mutate(sample_id = str_remove_all(sample_id, '_S.*$')) %>%
  mutate(sample_id = str_remove_all(sample_id, '20260331_')) %>%
  mutate(sample_id = tolower(sample_id))

# 2022 run nextseq
retention_2022_nextseq <- read_csv(here(fastq, 
                                   'nextseq_2022_run2', 'fixed', 'qc_plots',
                                   '20260331_peco2022_nextseq-library2_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2022) %>%
  mutate(seqmethod = 'nextseq') %>%
  # remove tail of sample name
  mutate(sample_id = str_remove_all(sample_id, '_S.*$')) %>%
  mutate(sample_id = str_remove_all(sample_id, '20260331_')) %>%
  mutate(sample_id = tolower(sample_id))

# retention 2023
retention_2023_nextseq <- read_csv(here('rawdata', 'peco', 'fastq', '2023', 
                                   '20250428_peco2023_12s_20240907_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2022) %>%
  mutate(seqmethod = 'nextseq')

raw_2023 <- read_csv(here('rawdata', 'peco', 'fastq', '2023', 
                                   '20250428_peco2023_12s_20240907_read-retention_12s_bysample-rawonly.csv')) %>%
  janitor::clean_names() %>%
    mutate(sample_id = str_remove_all(x1, '/Users/katesheridan/Documents/GitHub/chapter2/rawdata/peco/fastq/12S_PECO2023_Run20240907/Analysis/1/Data/fastq/fixed/20240923_')) %>%
  select(!x1) %>%
  # remove tail of sample name
  mutate(sample_id = str_remove_all(sample_id, '_S.*$'))

cutadapt_2023 <- read_csv(here('rawdata', 'peco', 'fastq', '2023', 
                                   '20250428_peco2023_12s_20240907_read-retention_12s_bysample-cutadaptonly.csv')) %>%
  janitor::clean_names() %>%
  # why is this here, remove
  mutate(sample_id = str_remove_all(x1, '/Users/katesheridan/Documents/GitHub/chapter2/rawdata/peco/fastq/12S_PECO2023_Run20240907/Analysis/1/Data/fastq/fixed/cutadapt/20240923_'))%>%
  select(!x1) %>%
  # remove tail of sample name
  mutate(sample_id = str_remove_all(sample_id, '_S.*$'))

retention_2023_nextseq_all <- retention_2023_nextseq %>%
  # remove beginning and end of sample name
  mutate(sample_id = str_remove_all(sample_id, 'filtered20240923_')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S.*$')) %>%
  full_join(raw_2023) %>%
  left_join(cutadapt_2023) %>%
  # if NA, dropped out, 0
  mutate(across(.cols = everything(), ~replace(., is.na(.), 0))) %>%
  # match sample names
  mutate(sample_id = tolower(sample_id)) %>%
        mutate(sample_id = case_when(str_detect(sample_id, 'pecoe-8') ~ 
                                 str_replace_all(sample_id, 'pecoe-8', 'pecoe-08'),
                                 str_detect(sample_id, 'pecoe-9') ~ 
                                 str_replace_all(sample_id, 'pecoe-9', 'pecoe-09'),
                               TRUE ~ sample_id))
```





```{r merge-retention}

retention_all <- retention_2021_1 %>%
  bind_rows(retention_2021_2) %>%
  bind_rows(retention_2021_2redo) %>%
  bind_rows(retention_2022_1) %>%
  bind_rows(retention_2022_2) 

retention_summary <- retention_all %>%
  group_by(year) %>%
  summarize(n_samp = length(sample_id),
            raw = sum(raw_f) + sum(raw_r),
            after_cutadapt = sum(cutadapt_f) + sum(cutadapt_r),
            # get the rs for this on the summary
            after_filtertrim = sum(filtertrim_f) + sum(filtertrim_r),
            after_denoise = sum(denoised_f) + sum (denoised_r),
            merged = sum(merged),
            nosingletons = sum(nosingletons),
            nochimeras = sum(nochimeras)) %>%
  ungroup() %>%
  janitor::adorn_totals('row')


write.csv(retention_summary, here(fastq_combined, 
                                  paste0(datefield, runfield,
                                         "read_retention.csv")))
```



# basic data exploration


```{r raw-reads}
miseq_2022_summary <- retention_2022_miseq %>%
  mutate(raw_total = raw_f + raw_r) %>%
  select(sample_id, raw_total, nochimeras) %>%
  summarise(mean_raw = mean(raw_total),
            median_raw = median(raw_total),
            mean_end = mean(nochimeras),
            median_end = median(nochimeras),
            total_raw = sum(raw_total),
            total_end = sum(nochimeras),
            max_raw = max(raw_total),
            max_end = max(nochimeras),
            sd_raw = sd(raw_total),
            sd_end = sd(nochimeras),
            q_25 = quantile(raw_total, probs = .25),
            q_75 = quantile(raw_total, probs = .75),
            iqr_raw = q_75 - q_25,
            coefvar_raw = 100 * sd_raw / mean_raw
            ) %>%
  mutate(year = 2022) %>%
  mutate(seqmethod = 'miseq')


nextseq_2022_summary <- retention_2022_nextseq %>%
  mutate(raw_total = raw_f + raw_r) %>%
  select(sample_id, raw_total, nochimeras) %>%
  summarise(mean_raw = mean(raw_total),
            median_raw = median(raw_total),
            mean_end = mean(nochimeras),
            median_end = median(nochimeras),
            total_raw = sum(raw_total),
            total_end = sum(nochimeras),
            max_raw = max(raw_total),
            max_end = max(nochimeras),
            sd_raw = sd(raw_total),
            sd_end = sd(nochimeras),
            q_25 = quantile(raw_total, probs = .25),
            q_75 = quantile(raw_total, probs = .75),
            iqr_raw = q_75 - q_25,
            coefvar_raw = 100 * sd_raw / mean_raw
            ) %>%
  mutate(year = 2022) %>%
  mutate(seqmethod = 'nextseq')

nextseq_2023_summary <- retention_2023_nextseq_all %>%
  mutate(raw_total = raw_f + raw_r) %>%
  select(sample_id, raw_total, nochimeras) %>%
  summarise(mean_raw = mean(raw_total),
            median_raw = median(raw_total),
            mean_end = mean(nochimeras),
            median_end = median(nochimeras),
            total_raw = sum(raw_total),
            total_end = sum(nochimeras),
            max_raw = max(raw_total),
            max_end = max(nochimeras),
            sd_raw = sd(raw_total),
            sd_end = sd(nochimeras),
            q_25 = quantile(raw_total, probs = .25),
            q_75 = quantile(raw_total, probs = .75),
            iqr_raw = q_75 - q_25,
            coefvar_raw = 100 * sd_raw / mean_raw
            ) %>%
  mutate(year = 2023) %>%
  mutate(seqmethod = 'nextseq')

summaries <- nextseq_2022_summary %>%
  rbind(miseq_2022_summary) %>%
  rbind(nextseq_2023_summary)
```




```{r}
retention_2022_miseq %>%
  mutate(raw_total = raw_f + raw_r) %>%
  ggplot() +
  geom_histogram(aes(x=raw_total)) +
  scale_x_continuous(labels = scales::comma)

retention_2022_nextseq %>%
  mutate(raw_total = raw_f + raw_r) %>%
  ggplot() +
  geom_histogram(aes(x=raw_total)) +
  scale_x_continuous(labels = scales::comma)

retention_2023_nextseq_all %>%
  mutate(raw_total = raw_f + raw_r) %>%
  ggplot() +
  geom_histogram(aes(x=raw_total)) +
  scale_x_continuous(labels = scales::comma)
```


