---
title: "ch2_01b-2023_edna-qc"
output: html_document
date: "2024-06-04"
---

Updated sept 25 2024 to include lulu etc.

```{r setup, include=FALSE}
library(tidyverse)
library(here)


# here filepaths
# In
fastq <- here('rawdata', 'peco', 'fastq', 
              '12S_PECO2023_Run20240907', 
              'Analysis', '1', 'Data', 
              'fastq', 'fixed', 'processed') 
# Out
edna_combined <- here('processeddata', 'peco', '2021-24_edna')
edna_out <- here('processeddata', 'peco', '2023_edna')

# fields
datefield <- '20250711_'
runfield <- 'peco-2023_12s_'
```


# Load In

```{r load-in}
metadata <- read_csv(here(edna_combined, '20240925_peco-combined_metadata.csv')) %>%
  filter(year == 2023) %>%
  # remove 2023s at the end of pcr negatives; woops
  mutate(sample_id = str_replace_all(sample_id, '-2023$', ''))

taxonomy <- read_csv(here(edna_combined, '20250528_peco-combined_12s_taxonomy.csv'))

motu2asvs <- read_csv(here('rawdata', 'peco', 
                           'fastq', 'allyears', 
                           '20250528_peco-combined_12s_lulu_motu2asv.csv'))

asvtable <- read_delim(here(fastq,
                            '20250528_peco-combined_12s_sequence-table_asv-names_2023.txt'))
```




```{r merge}
motumatrix_metadata <- asvtable %>%
  # pivot to long so sequence can map to ASV
  pivot_longer(cols = !sample,
               names_to = 'asv') %>%
  filter(value >= 1) %>% 
  mutate(sample = tolower(sample)) %>%
  mutate(sample_id = sample) %>%
      mutate(sample_id = case_when(str_detect(sample_id, 'pecoe-8') ~ 
                                 str_replace_all(sample_id, 'pecoe-8', 'pecoe-08'),
                                 str_detect(sample_id, 'pecoe-9') ~ 
                                 str_replace_all(sample_id, 'pecoe-9', 'pecoe-09'),
                               TRUE ~ sample_id)) %>%
  filter(sample_id %in% metadata$sample_id) %>%
  left_join(taxonomy) %>%
  mutate(motu_pa = 1) %>%
  rename(reads_raw = value) %>%
  left_join(metadata) %>%
    # remove columns that don't matter this year
  janitor::remove_empty() %>%
  # check before removing
  select(!c(motu_swarm, curated, lulu_rank)) 

```

Lab controls here

## Lab controls

Subtracting reads from pcr / extraction controls

labs; 
extraction negative -- group = extraction date | extraction blank = xn###
pcr negative -- group == library
Field blank -- group = site


```{r control-subtract}
# this will need to be expanded with more data + lab metadata
pcr_ctrl <- motumatrix_metadata %>%
  filter(treatment == 'PCR blank') %>%
  select(sample_id, library, asv, reads_raw, found_taxa) %>%
  mutate(pcrasv = paste0(library, '_', asv)) %>%
  select(pcrasv, reads_raw, found_taxa) %>%
  rename(reads_pcr = reads_raw)

# needs done when extraction info is given
extract_ctrl <- motumatrix_metadata %>%
  filter(treatment == 'Extraction blank') %>%
  select(sample_id, asv, reads_raw, found_taxa) %>%
  # make single code that combines site and motu
  mutate(extractasv = paste0(sample_id, '_', asv)) %>%
  select(extractasv, reads_raw, found_taxa) %>%
  rename(reads_control = reads_raw)

motumatrix_metadata_nolab <- motumatrix_metadata %>%
  # insert minus part here
  # subtract extraction controls
  # single code to combine site and motu
  mutate(extractasv = paste0(extraction_blank, '_', asv)) %>%
  # merge to have field control values for each site-motu combo
  left_join(extract_ctrl) %>%
  mutate(in_ctrl_extract = ifelse(reads_control > 0, 'yes', NA_character_)) %>%
  #subtract control reads from regular reads
  mutate(reads_adjust = reads_raw - reads_control) %>%
  mutate(reads_adjust = coalesce(reads_adjust, reads_raw)) %>%
  mutate(reads_adjust = ifelse(reads_adjust <= 0, 0, reads_adjust)) %>%
  ## keeping motus that are negative for now to look into removal
  # only samples that still have reads
  #filter(reads_adjust > 0) %>%
  select(!(c(extractasv))) %>%
  ## until pcr reads are subtracted
  #rename(reads_adjust_lab = reads_adjust) %>%
  # subtract pcr controls by library
  # ### I think it's by plate
  # single code to combine library and motu
  mutate(pcrasv = paste0(library, '_', asv)) %>%
  # merge to have field control values for each site-motu combo
  left_join(pcr_ctrl) %>%
  mutate(in_ctrl_pcr = ifelse(reads_pcr > 0, 'yes', NA_character_)) %>%
  #subtract control reads from regular reads
  mutate(reads_adjust_pcr = reads_raw - reads_pcr) %>%
  mutate(reads_adjust_lab = (reads_adjust_pcr - reads_adjust)) %>%
  mutate(reads_adjust_lab = coalesce(reads_adjust_lab, reads_adjust_pcr, reads_adjust)) %>%
  mutate(reads_adjust_lab = ifelse(reads_adjust_lab <= 0, 0, reads_adjust_pcr)) %>%
  #mutate(in_ctrl_lab = ifelse((reads_control > 0|reads_pcr > 0), 'yes', 'no')) %>%
  mutate(reads_adjust_lab = coalesce(reads_adjust_lab, reads_raw)) %>%
  ## keeping motus without reads for now
  # only motus that still have reads
  #filter(reads_adjust_lab > 0) %>%
  select(!(c(reads_pcr, reads_control, reads_adjust_pcr, reads_adjust, pcrasv))) %>%
  #rename(reads_raw = reads) %>%
  # n site code = lab control
  filter(!(is.na(site_code))) %>%
  mutate(ctrl_lab0 = ifelse(reads_adjust_lab == 0, 'yes', 'no')) %>%
  # remove unneeded lab based columns
  relocate(in_ctrl_extract, in_ctrl_pcr, reads_adjust_lab, ctrl_lab0, .before = kingdom)
  

```




#### note: site code is not unique
```{r field-control}
field_ctrl <- motumatrix_metadata_nolab %>%
  filter(treatment == 'Field blank') %>%
  select(sample_id, site_code, asv, reads_raw, found_taxa) %>%
  # make single code that combines site and motu
  mutate(siteasv = paste0(site_code, '_', asv)) %>%
  select(siteasv, reads_raw) %>%
  rename(reads_control = reads_raw) 


motumatrix_metadata_nofield <- motumatrix_metadata_nolab %>%
  # single code to combine site and motu
  mutate(siteasv = paste0(site_code, '_', asv)) %>%
  # merge to have field control values for each site-motu combo
  left_join(field_ctrl) %>%
  #subtract control reads from regular reads
  mutate(reads_adjust = reads_adjust_lab - reads_control) %>%
  mutate(reads_adjust = coalesce(reads_adjust, reads_adjust_lab)) %>%
  mutate(reads_adjust = ifelse(reads_adjust <= 0, 0, reads_adjust)) %>%
  mutate(ctrl_fieldlab0 = ifelse(reads_adjust == 0, 'yes', 'no')) %>%
  mutate(in_ctrl_field = ifelse(reads_control > 0, 'yes', 'no')) %>%
  mutate(reads_adjust = coalesce(reads_adjust, reads_raw)) %>%
  # only samples that still have reads
  #filter(reads_adjust > 0) %>%
  #subtract control reads from raw reads
  mutate(reads_adjust_field = reads_raw - reads_control) %>%
  mutate(reads_adjust_field = coalesce(reads_adjust_field, reads_raw)) %>%
  mutate(reads_adjust_field = ifelse(reads_adjust_field <= 0, 0, reads_adjust_field)) %>%
  select(!(c(reads_control, siteasv))) %>%
  #relocate(reads_adjust, .before = reads_raw) %>%
  mutate(ctrl_field0 = ifelse(reads_adjust_field == 0, 'yes', 'no')) %>%
  relocate(reads_adjust, in_ctrl_field, reads_adjust_field, ctrl_field0, ctrl_fieldlab0, .before = reads_adjust_lab) %>%
  rename(reads_adjust_fieldlab = reads_adjust) %>%
  select(!c(n_dups))

```

# fish only
```{r}
#check options
unique(motumatrix_metadata_nofield$class)

#select only fish
motumatrix_metadata_fish <- motumatrix_metadata_nofield %>%
  filter(class %in% c('Teleostei', 'Chondrostei', 'Holocephali', 'Elasmobranchii'))

write_csv(motumatrix_metadata_fish, here(edna_out,
                                         paste0(datefield, 'peco2023_12s-asvmatrix_fish-temp.csv')))


write_csv(motumatrix_metadata_nofield, here(edna_out, paste0(datefield, 'peco2023_12s-asvmatrix-temp.csv')))

```

# simple version
```{r}
asvmatrix_simple <- motumatrix_metadata_nofield %>%
  # excess columns for this version
  select(!c(biological_observations,
            #general_notes, 
            #swell_height_m, 
            tide, wind, rain,
            #site_or_sampling_description, 
            organization_participants)) %>%
  #reads together
  relocate(reads_raw, reads_adjust_lab, reads_adjust_field, .before = reads_adjust_fieldlab)


write_csv(asvmatrix_simple, here(edna_out, paste0(datefield, 'peco2023_12s-asvmatrix-simple.csv')))


# add controls

# this will need to be expanded with more data + lab metadata
lab_controls_to_merge <- motumatrix_metadata %>%
  filter(treatment %in% c('PCR blank', 'Extraction blank', 'Field blank')) %>%
    # excess columns for this version
  select(!c(biological_observations,
             tide, wind, rain,organization_participants))
  

write_csv(lab_controls_to_merge, here(edna_out, paste0(datefield, 'peco2023_12s_controls.csv')))

```





