---
title: "ch2-mapping"
author: "Kate Sheridan"
date: "`r Sys.Date()`"
output: html_document
---

This document makes maps of the partners and sites.


```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(sf)
library(PNWColors)
library(ggpubr)

# here filepath
plotdata <- here('processeddata', 'peco', '2021-24_edna')

datefield <- '20260927_'

# make palette obect from pnwpalettes
# region name
#pal <- pnw_palette("Bay", 15, type = "continuous")

# manual with 2 oregon regions
pal_2or <- c("Juneau Region, Alaska" = "#00496F",
             "Southeast Alaska" = "#03587B",
             "Haida Gwaii, British Columbia" = "#076787",
             "Central Coast British Columbia" = "#0B7693",
             "North Vancouver Island, British Columbia" = "#0F85A0",
             "Inner Coast, British Columbia" = "#469989",
             "Pacific Rim Park, British Columbia" = "#7EAE73",
             "Puget Sound & Padilla Bay, Washington" = "#B5C25C",
             "Willapa Bay, Washington" = "#EDD746",
             "Yaquina Bay, Oregon" = "#EDC334",
             "Coos Bay, Oregon" = "#EDB123",
             "Humboldt Bay, California" = "#ED9E11",
             "Bodega Bay, California" = "#ED8B00",
             "San Fransisco Bay, California" = "#E97809",
             "Morro Bay, California" = "#E56512",
             "Los Angeles, California" = "#E1531B",
             "San Diego region, California" = "#DD4124")
```

# load in data
```{r load-in}
# load in csvs
edna_meta <- read_csv(here(plotdata, 
                           "20240925_peco-combined_metadata.csv")) %>%
  rename(region_label = region_name_label) %>%
  janitor::remove_empty()

region_plotting <- read_csv(here(plotdata,
                                 "20240925_peco_region-name-plotting.csv"))[-1] %>%
  rename(region_label = region_name_label)

# set up labels and colors for region
region_by_lat <- region_plotting %>%
  dplyr::select(region_name, avg_region_lat,
         region_label, region_lat_name) %>%
  distinct() %>%
  arrange(-avg_region_lat)

# stripped down edna coordinates, one per site
ednacoord <- edna_meta %>%
  select(region_code, region_name, site_code, location_name, 
         decimal_latitude, decimal_longitude) %>%
  #mutate(region_code = as.factor(region_code)) %>%
  left_join(region_by_lat) %>%
  arrange(avg_region_lat) %>%
  distinct() %>%
  filter(!(is.na(region_code)))
```

# Shapefile 

First making the base map for the coast, original shapefiles made in QGIS

```{r shapefile-map}
land <- st_read(here('rawdata', 'spatial',
                     'clippedpacific', 'pacific-coast-clip.shp'))

# convert to lat-long
land_t <- st_transform(land, "EPSG:4326")

# make a bounding box
land_bbox <- st_bbox(c(xmin = -137, xmax = -114, ymin = 31, ymax = 60), 
                     crs = "EPSG:4326")

# st_crop to use the bounding box to crop the original object
land_crop <- st_crop(land_t, land_bbox)

wcsf_map <- ggplot(land_crop) +
  geom_sf(fill = 'white', 
          color = 'grey50') +
  xlim(min(-136, 
    na.rm = T), 
    max(-115, na.rm = T)) +
  ylim(min(32.45, na.rm = T), 
       max(58.6, na.rm = T)) + 
  theme_classic() +
    theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA, size = .5),
        axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = 'grey80'))

# save blank maps
ggsave(wcsf_map, filename =  here('output', 'maps', 
                                 'westcoast_blank.png'), 
       device = "png", 
       dpi = 300, 
       width = 6, 
       height = 7, 
       units = "in")
ggsave(wcsf_map, filename =  here('output', 'maps', 
                                 'westcoast_blank.pdf'), 
       device = "pdf", 
       width = 5, 
       height = 7, 
       units = "in")
```


# Maps by site

```{r peco-maps}
# sized for png
peco_sf <- wcsf_map + geom_point(data = ednacoord, 
                                 aes(x = decimal_longitude, 
                                   y = decimal_latitude,
                                   # order by latitude
                                   fill = factor(region_label, 
                                                 levels = region_by_lat$region_label)),
                                 color = 'black',
                                 shape = 21,
             size = 2.5, alpha = .95)+
  scale_fill_manual(values = pal_2or) +
  theme(legend.text = element_text(size = 5)) +
    labs(fill = 'Region', 
       title = "Pacific eDNA Coastal Observatory",
       x = NULL, y = NULL)


ggsave(peco_sf, filename =  here('output', 'maps', 
                                 paste0(datefield, 'map_edna_2021-24.png')), 
       device = "png", 
       dpi = 300, 
       width = 6, 
       height = 7, 
       units = "in")


# sized for pdf
wcsf_map + geom_point(data = ednacoord, 
                      aes(x = decimal_longitude, 
                          y = decimal_latitude,
                          # order by latitude
                          fill = factor(region_label, 
                                        levels = region_by_lat$region_label)),
                      color = 'black',
                      shape = 21,
                      size = 3.5, 
                      alpha = .95)+
  scale_fill_manual(values = pal_2or) +
  theme(legend.text = element_text(size = 10)) +
    labs(fill = 'Region', 
       title = "Pacific eDNA Coastal Observatory",
       x = NULL, y = NULL)


ggsave(filename =  here('output', 'maps',
                        paste0(datefield, 'map_edna_2021-24.pdf')), 
       device = "pdf", 
       dpi = 300, 
       width = 11.5, 
       height = 14, 
       units = "in")


# facet by year

# stripped down edna coordinates, one per site
ednacoord_year <- edna_meta %>%
  select(region_code, site_code, location_name, year,
         decimal_latitude, decimal_longitude, region_label) %>%
  mutate(region_code = as.factor(region_code)) %>%
  left_join(region_by_lat) %>%
  arrange(avg_region_lat) %>%
  distinct() %>%
  filter(!(is.na(region_code)))


by_year <- wcsf_map + geom_point(data = ednacoord_year, 
                                 aes(x = decimal_longitude, 
                                   y = decimal_latitude,
                                   fill = factor(region_label,
                                                 levels = region_by_lat$region_label)),
                                 color = 'black',
                                 shape = 21,
             size = 2.5, alpha = .95)+
  facet_wrap(~year) +
  scale_fill_manual(values = pal_2or) +
  theme(
        legend.text = element_text(size = 15),
        strip.text = element_text(size = 20)) +
    labs(title = "Pacific eDNA Coastal Observatory",
         fill = NULL, x = NULL, y = NULL)

ggsave(filename =  here('output', 'maps', 
                        paste0(datefield, 'map_edna_2021-24_facet.png')), 
       device = "png", dpi = 300, width = 16, height = 7, units = "in")

```


# centroids

geosphere can calculate centroids

```{r centroids}
peco_cent <- ednacoord %>%
  dplyr::select(region_name, decimal_longitude, decimal_latitude) %>%
  distinct() %>%
  add_count(region_name) %>%
  # needs at least 3 sites to be a polygon
  filter(n > 2) %>%
  dplyr::select(!n) 

# empty df
centroids_by_region <- c()

# for each site calculate the centroids
for (region in peco_cent$region_name){
  # filter to sites in only one region
  # make into matrix
    sites <- peco_cent %>%
      filter(region_name == region) %>%
      dplyr::select(!region_name) %>%
      arrange(decimal_latitude) %>%
      as.matrix()
    
    # run centroid
    region_cent <- geosphere::centroid(sites)
    # format to output
    region_cent_df <- as.data.frame(region_cent)
    region_cent_df$region_name <- region
    
    #append to dataframe
    centroids_by_region <- bind_rows(centroids_by_region, region_cent_df) %>%
      distinct()
  }

all_centroids <- ednacoord %>%
  dplyr::select(region_name, decimal_longitude, decimal_latitude) %>%
  distinct() %>%
  add_count(region_name) %>%
  # needs at least 3 sites to be a polygon
  # lets get the ones that didn't make it
  filter(n < 3) %>%
  dplyr::select(!n) %>%
  group_by(region_name) %>%
  summarise(lat = mean(decimal_latitude), 
            lon = mean(decimal_longitude)) %>%
  ungroup() %>%
  bind_rows(centroids_by_region) %>% 
  left_join(region_by_lat) %>%
  dplyr::select(!avg_region_lat) %>%
  arrange(region_lat_name)

write_csv(all_centroids, here('processeddata', 'peco', '2021-24_edna', 
                              paste0(datefield, 'peco_regioncentroids.csv')))
```

```{r map centroids}
wcsf_map + geom_point(data = all_centroids, 
                      aes(x = lon, 
                          y = lat,
                          fill = factor(region_label,
                                        levels = region_by_lat$region_label)),
                      color = 'black',
                      shape = 21,
                      size = 2.5, 
                      alpha = .95)+
  scale_fill_manual(values = pal_2or) +
  theme(legend.position = 'none')

ggsave(filename =  here('output', 'maps', 
                                 paste0(datefield, 'map_edna_2021-24_centroids.png')), 
       device = "png", dpi = 300, width = 6, height = 7, units = "in")

# pdf versions
wcsf_map + geom_point(data = all_centroids, 
                      aes(x = lon,  
                          y = lat,
                          fill = factor(region_label,
                                        levels = region_by_lat$region_label)),
                      color = 'black',
                      shape = 21,
                      size = 2.5, 
                      alpha = .95)+
  scale_fill_manual(values = pal_2or) +
  theme(legend.position = 'none')+
    labs(x = NULL, y = NULL)

ggsave(filename =  here('output', 'maps', 
                        paste0(datefield, 'map_edna_2021-24_centroids.pdf')), 
       device = "pdf", dpi = 300, width = 2.5, height = 4, units = "in")
```

Those are the most basic maps!

```{r blue vers}
# 7693B8
# 262F3C
wcsf_map_blue <- ggplot(land_t) +
  geom_sf(fill = 'white', 
          color = '#262F3C') +
  xlim(min(-145, 
    na.rm = T), 
    max(-115, na.rm = T)) +
  ylim(min(28, na.rm = T), 
       max(61, na.rm = T)) + 
  theme_classic() +
    theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA, size = .5),
        axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = '#7693B8'))

wcsf_map_blue

# save blank maps
ggsave(wcsf_map_blue, filename =  here('output', 'maps', 
                                 'westcoast_blank-blue.png'), 
       device = "png", 
       dpi = 300, 
       width = 6, 
       height = 8, 
       units = "in")

wcsf_map_blue + geom_point(data = all_centroids, 
                      aes(x = lon, 
                          y = lat,
                          fill = factor(region_label,
                                        levels = region_by_lat$region_label)),
                      color = 'black',
                      shape = 21,
                      size = 2.5, 
                      alpha = .95)+
    xlim(min(-136, 
    na.rm = T), 
    max(-115, na.rm = T)) +
  ylim(min(32.45, na.rm = T), 
       max(58.6, na.rm = T)) + 
  scale_fill_manual(values = pal_2or) +
  theme(legend.position = 'none')

ggsave(filename =  here('output', 'maps', 
                                 paste0(datefield, 'map_edna_2021-24_centroids-blue.png')), 
       device = "png", dpi = 300, width = 6, height = 7, units = "in")

```

