---
title: "ch2-map-obisgbif-to-sites"
author: "Kate Sheridan"
date: "`r Sys.Date()`"
output: html_document
---

Subsetting obis/gbif data by regions and taxa


```{r setup, include=FALSE}
library(tidyverse)
library(here)

library(sf)
library(geosphere)
# here filepath
bigdata <- here('processeddata','bigdata')

datefield <- '20251113_'

# from PNW colors, Bay
# or with 2 oregon regions
pal_2or <- c("Juneau Region, Alaska" = "#00496F",
             "Southeast Alaska" = "#03587B",
             "Haida Gwaii, British Columbia" = "#076787",
             "Central Coast British Columbia" = "#0B7693",
             "North Vancouver Island, British Columbia" = "#0F85A0",
             "Inner Coast, British Columbia" = "#469989",
             "Pacific Rim Park, British Columbia" = "#7EAE73",
             "Puget Sound & Padilla Bay, Washington" = "#B5C25C",
             "Willapa Bay, Washington" = "#EDD746",
             "Yaquina Bay, Oregon" = "#EDC334",
             "Coos Bay, Oregon" = "#EDB123",
             "Humboldt Bay, California" = "#ED9E11",
             "Bodega Bay, California" = "#ED8B00",
             "San Francisco Bay, California" = "#E97809",
             "Morro Bay, California" = "#E56512",
             "Los Angeles, California" = "#E1531B",
             "San Diego region, California" = "#DD4124")
```

```{r load-in}
# whole dataset
bigdat <- read_csv(here(bigdata, '20250626_obis-gbif_merge-fish.csv'))

peco_sites <- read_csv(here('processeddata', 'peco', '2021-24_edna', 
                            '20251113_peco_region-name-plotting.csv'))[-1] %>%
  mutate(region_name2 = case_when(region_name == 'CA_SF' ~ 'CA_NC',
                                  TRUE ~ region_name)) %>%
  select(!c(region_code_label, samples, region_code, sites)) %>%
  distinct()
```




# split to regions

unique coordinates only for now

## PECO

subsets that are parallel to PECO

```{r peco-subsets}
# within-PECO
peco_sub <- bigdat %>% 
  filter(decimal_latitude > 27) %>%
  filter(decimal_latitude < 60) %>%
  filter(decimal_longitude > -136) %>%
  filter(decimal_longitude < -115) %>%
  mutate(peco_region = case_when(decimal_latitude < 33 ~ 'CA_SD',
                                 decimal_latitude < 34 ~ 'CA_LA',
                                 decimal_latitude < 36 ~ 'CA_MB',
                                 decimal_latitude < 39.5 ~ 'CA_NC',
                                 decimal_latitude < 42 ~ 'CA_HB',
                                 decimal_latitude < 44 ~ 'OR_CB',
                                 decimal_latitude <= 45.3 ~ 'OR_YB',
                                 decimal_latitude <= 48 &
                                   decimal_longitude <= -123.5 ~ 'WA_WB',
                                 decimal_latitude <= 49.4 &
                                   decimal_longitude > -123.8 ~ 'WA_PS',
                                 # Pacific rim park  and inner coast largely split by longitude
                                 decimal_latitude < 49 & decimal_longitude <= -123.8 ~ 'BC_PP',
                                 decimal_latitude < 49.5 & decimal_longitude <= -125 ~ 'BC_PP',
                                 decimal_latitude < 49.9 & decimal_longitude < -126 ~ 'BC_PP',
                                 decimal_latitude <51 & decimal_longitude > -126 ~ 'BC_IC',
                                 decimal_latitude <51 ~ 'BC_NV',
                                 decimal_latitude < 53 & 
                                   decimal_longitude > -130 ~ 'BC_CC',
                                 decimal_latitude < 54.5 ~ 'BC_HG',
                                 decimal_latitude < 57 ~ 'AK_SE',
                                 decimal_latitude <= 60 ~ 'AK_JN'))

peco_regions <- peco_sites %>%
    select(!(c(site_code, decimal_latitude, decimal_longitude))) %>%
  distinct()

peco_sub_map <- peco_sub %>% # set up peco sites
  left_join(peco_regions, by = c('peco_region' = 'region_name2'))
```

### PECO-sites

```{r PECO-sites}
by_site <- peco_sub %>%
  # set up peco sites
  left_join(peco_sites, by = c('peco_region' = 'region_name2')) %>%
  distinct() %>%
  rename(lat_peco = decimal_latitude.y,
         long_peco = decimal_longitude.y,
         lat_obis = decimal_latitude.x,
         long_obis = decimal_longitude.x) %>%
  # for some reason it needs this call
  rowwise() %>%
  mutate(distance_m = distm(c(long_peco, lat_peco), c(long_obis, lat_obis))) %>%
  group_by(lat_obis, long_obis) %>%
  mutate(shortest_m = min(distance_m)) %>%
  filter(distance_m == shortest_m) %>%
  select(!(c(distance_m, freshwater_only,
             lat_peco, long_peco))) %>%
  filter(shortest_m < 100000) %>%
  rename(decimal_latitude = lat_obis,
         decimal_longitude = long_obis) %>%
  distinct()

write_csv(by_site, 
          here(bigdata,
               paste0(datefield, 'obis-gbif_region-peco-bysite_unfiltered.csv')))
  
```

# Mapping

Grey to match plots; blue to match presentations
one for all, sorted, filtered
```{r basic-map}
land <- st_read(here('rawdata', 'spatial',
                     'clippedpacific', 'pacific-coast-clip.shp'))

# convert to lat-long
land_t <- st_transform(land, "EPSG:4326")

# make a bounding box
land_bbox <- st_bbox(c(xmin = -137, xmax = -114, ymin = 31, ymax = 60), 
                     crs = "EPSG:4326")

# st_crop to use the bounding box to crop the original object
land_crop <- st_crop(land_t, land_bbox)

wcsf_map <- ggplot(land_crop) +
  geom_sf(fill = 'white', 
          color = 'grey50') +
  xlim(min(-136, 
    na.rm = T), 
    max(-115, na.rm = T)) +
  ylim(min(32.45, na.rm = T), 
       max(58.6, na.rm = T)) + 
  theme_classic() +
    theme(axis.title = element_blank(),
        #axis.text = element_blank(),
        #axis.ticks.x = element_blank(),
        axis.line = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA, size = .5),
        #axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = 'grey80'))

wcsf_map+ 
  geom_point(data = bigdat, 
             aes(x = decimal_longitude, 
                 y = decimal_latitude),
             color = '#57a7ad',
             alpha = .08) +
  geom_point(data = peco_sites, 
             aes(x = decimal_longitude, 
                 y = decimal_latitude),
             color = '#5d81af')

ggsave(here('output', 'maps', paste0(datefield, 'obis-gbif_nofilter.png')))



wcsf_map+ 
  geom_point(data = peco_sub_map, 
             aes(x = decimal_longitude, 
                 y = decimal_latitude,
                 col = region_name_label),
             alpha = .08) +
  scale_color_manual(values = pal_2or)+
  geom_point(data = peco_sites, 
             aes(x = decimal_longitude, 
                 y = decimal_latitude,
                 fill = region_name_label),
             color = 'black',
             shape = 21) +
  scale_fill_manual(values = pal_2or) +
  theme(legend.position = 'none')

ggsave(here('output', 'maps', paste0(datefield, 'obis-gbif_peco-regions.png')))


wcsf_map+ 
  geom_point(data = by_site, 
             aes(x = decimal_longitude, 
                 y = decimal_latitude,
                 col = region_name_label),
             #color = '#57a7ad',
             alpha = .08) +
  scale_color_manual(values = pal_2or) +
  geom_point(data = peco_sites, 
             aes(x = decimal_longitude, 
                 y = decimal_latitude,
                 fill = region_name_label),
             color = 'black',
             shape = 21) +
  scale_fill_manual(values = pal_2or) +
  theme(legend.position = 'none')

ggsave(here('output', 'maps', paste0(datefield, 'obis-gbif_peco-sites.png')))
```


## presentation version

```{r presentation maps}
wcsf_map_blue <- ggplot(land_t) +
  geom_sf(fill = 'white', 
          color = '#262F3C') +
  xlim(min(-145, 
    na.rm = T), 
    max(-115, na.rm = T)) +
  ylim(min(28, na.rm = T), 
       max(61, na.rm = T)) + 
  theme_classic() +
    theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line = element_blank(),
        panel.border = element_rect(colour = "black", fill = NA, size = .5),
        axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = '#7693B8'))

wcsf_map_blue

wcsf_map_blue + 
    geom_point(data = by_site, 
             aes(x = decimal_longitude, 
                 y = decimal_latitude,
                 col = region_name_label),
             alpha = .08) +
  scale_color_manual(values = pal_2or) +
  geom_point(data = peco_sites, 
             aes(x = decimal_longitude, 
                 y = decimal_latitude,
                 fill = region_name_label),
             color = 'black',
             shape = 21) +
  scale_fill_manual(values = pal_2or) +
    xlim(min(-145, 
    na.rm = T), 
    max(-115, na.rm = T)) +
  ylim(min(28, na.rm = T), 
       max(61, na.rm = T)) + 
  theme(legend.position = 'none')

ggsave(filename =  here('output', 'maps', 
                                 paste0(datefield, 'map_obisgbif-site-blue.png')), 
       device = "png", dpi = 300, width = 8, height = 12, units = "in")


wcsf_map_blue +
    geom_point(data = peco_sub_map, 
             aes(x = decimal_longitude, 
                 y = decimal_latitude,
                 col = region_name_label),
             alpha = .08) +
  scale_color_manual(values = pal_2or)+
  geom_point(data = peco_sites, 
             aes(x = decimal_longitude, 
                 y = decimal_latitude,
                 fill = region_name_label),
             color = 'black',
             shape = 21) +
  scale_fill_manual(values = pal_2or) +
      xlim(min(-145, 
    na.rm = T), 
    max(-115, na.rm = T)) +
  ylim(min(28, na.rm = T), 
       max(61, na.rm = T)) + 
  theme(legend.position = 'none')

ggsave(filename =  here('output', 'maps', 
                                 paste0(datefield, 'map_obisgbif-region-blue.png')), 
       device = "png", dpi = 300, width = 8, height = 12, units = "in")



```


# ranges

```{r}
range_obis <- peco_sub %>%
  select(scientific_name, decimal_latitude) %>%
  group_by(scientific_name) %>%
  mutate(max_lat = max(decimal_latitude)) %>%
  mutate(min_lat = min(decimal_latitude)) %>%
  ungroup() %>%
  select(!decimal_latitude) %>%
  distinct


records_bysite <- peco_sub %>%
  select(scientific_name, peco_region) %>%
  rename(region_name = peco_region) %>%
  distinct()

range_pecosite <- peco_sites %>%
  select(site_code, region_name, decimal_latitude) %>%
  left_join(records_bysite) %>%
  mutate(sp_pa = 1) %>%
  pivot_wider(id_cols = c(site_code, decimal_latitude),
              names_from = scientific_name,
              values_from = sp_pa) %>%
  pivot_longer(cols = !c(site_code, decimal_latitude),
               names_to = 'scientific_name') %>%
  left_join(range_obis) %>%
  mutate(site_inrange = case_when(decimal_latitude >= min_lat & decimal_latitude <= max_lat ~ 'In range',
                                  decimal_latitude < min_lat ~ 'South of range',
                                  decimal_latitude > max_lat ~ 'North of range')) %>%
  pivot_wider(id_cols = scientific_name,
              names_from = site_code,
              values_from = site_inrange)


write_csv(range_pecosite, here(bigdata, paste0(datefield, 'species-site_obis-ranges.csv')))
```

# check

```{r}
unique(peco_sub$year)
```

