---
title: "ch2-11_misc-stats"
author: "Kate Sheridan"
date: "`r Sys.Date()`"
output: html_document
---

This includes various things I need to report.
First, read retention by year.

```{r setup, include=FALSE}
library(tidyverse)
library(here)

retention_in <- here('rawdata', 'peco', 'fastq')

datefield <- '20251111_'
```

# read retention

```{r load in retention}
retention_2021_run1 <- read_delim(here(retention_in, '2021',
                                '20240611_12S_PECO_Run1_20220829_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2021)

retention_2021_run2 <- read_delim(here(retention_in, '2021',
                                '20240611_12S_PECO_2021_Lib2_Run20221108_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2021)

retention_2021_bsaredo <- read_delim(here(retention_in, '2021',
                                '20240611_12s_peco_redos_run20230109_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2021)

retention_2022 <- read_delim(here(retention_in, '2022',
                                '20250425_peco2022_12s_nextseq_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2022)

retention_2022_raw <- read_delim(here(retention_in, '2022',
                                '20250425_peco2022_12s_nextseq_read-retention_12s_bysample-rawonly.csv')) %>%
  janitor::clean_names() %>%
  mutate(year = 2022) %>%
  rename('sample_id' = 'x1') %>%
  mutate(sample_id = str_remove_all(sample_id, '^(.*)fixed\\/')) %>%
  mutate(sample_id = str_remove_all(sample_id, '\\.fastq\\.gz'))

retention_2022_cut <- read_delim(here(retention_in, '2022',
                                '20250425_peco2022_12s_nextseq_read-retention_12s_bysample-cutadaptonly.csv')) %>%
  janitor::clean_names() %>%
  mutate(year = 2022) %>%
  rename('sample_id' = 'x1') %>%
  mutate(sample_id = str_remove_all(sample_id, '^(.*)cutadapt\\/')) %>%
  mutate(sample_id = str_remove_all(sample_id, '\\.fastq\\.gz'))

retention_2022_miseq1 <- read_delim(here(retention_in, '2022',
                                '20221023_peco2022_12s_run1-20230523_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2022)

retention_2022_miseq2 <- read_delim(here(retention_in, '2022',
                                '20221023_peco2022_12s_run2-20230629_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2022)


retention_2023 <- read_delim(here(retention_in, '2023',
                                '20250428_peco2023_12s_20240907_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2023)

retention_2023_raw <- read_delim(here(retention_in, '2023',
                                '20250428_peco2023_12s_20240907_read-retention_12s_bysample-rawonly.csv')) %>%
  janitor::clean_names() %>%
  mutate(year = 2023) %>%
  rename('sample_id' = 'x1') %>%
  mutate(sample_id = str_remove_all(sample_id, '^(.*)fixed\\/')) %>%
  mutate(sample_id = str_remove_all(sample_id, '\\.fastq\\.gz'))

retention_2023_cut <- read_delim(here(retention_in, '2023',
                                '20250428_peco2023_12s_20240907_read-retention_12s_bysample-cutadaptonly.csv')) %>%
  janitor::clean_names() %>%
  mutate(year = 2023) %>%
  rename('sample_id' = 'x1') %>%
  mutate(sample_id = str_remove_all(sample_id, '^(.*)cutadapt\\/')) %>%
  mutate(sample_id = str_remove_all(sample_id, '\\.fastq\\.gz'))

retention_2024 <- read_delim(here(retention_in, '2024',
                                '20250527_peco2024_12s_read-retention_12s_bysample.csv'))[-1] %>%
  janitor::clean_names() %>%
  mutate(year = 2024)

retention_2024_raw <- read_delim(here(retention_in, '2024',
                                '20250527_peco2024_12s_read-retention_12s_bysample-rawonly.csv')) %>%
  janitor::clean_names() %>%
  mutate(year = 2024) %>%
  rename('sample_id' = 'x1') %>%
  mutate(sample_id = str_remove_all(sample_id, '^(.*)fixed\\/')) %>%
  mutate(sample_id = str_remove_all(sample_id, '\\.fastq\\.gz'))

retention_2024_cut <- read_delim(here(retention_in, '2024',
                                '20250527_peco2024_12s_read-retention_12s_bysample-cutadaptonly.csv')) %>%
  janitor::clean_names() %>%
  mutate(year = 2024) %>%
  rename('sample_id' = 'x1') %>%
  mutate(sample_id = str_remove_all(sample_id, '^(.*)cutadapt\\/')) %>%
  mutate(sample_id = str_remove_all(sample_id, '\\.fastq\\.gz'))


# 2022 we only have some of the miseq samples, not all
missing_samples <- read_csv(here('processeddata', 'peco', '2021-24_edna',
                                 '20250530sample_tracking.csv')) %>%
  filter(missing == 'missing')


retention_2024_cut[1,1]
```

```{r merge}
# 2021
retention_2021_miseq <- retention_2021_run1 %>%
  bind_rows(retention_2021_run2) %>%
  bind_rows(retention_2021_bsaredo) %>%
    mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{3}_L001_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{2}_L001_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{1}_L001_R1_001')) %>%
  mutate(sample_id = tolower(sample_id)) %>%
  # column for bsa redo
  mutate(bsa_redo = ifelse(str_detect(sample_id, 'bsaredo'), 'bsaredo', NA_character_)) %>%
  mutate(sample_id = str_remove_all(sample_id, '-bsaredo')) %>%
      # add a 0 for only ones with 100s
  mutate(sample_id = case_when(str_detect(sample_id, 'coe[0-9]{3}$') ~ str_replace(sample_id, 'coe', 'coe-0'),
                               str_detect(sample_id, 'coe[0-9]{4}$') ~ str_replace(sample_id, 'coe', 'coe-'),
                               str_detect(sample_id, 'pecoxn') ~ str_replace_all(sample_id, 'pecoxn', 'exblank-2021-'),
                               str_detect(sample_id, 'peco-neg-pcr-p') ~ str_replace_all(sample_id, 'peco-neg-pcr-p', 'negpcr-2021-'),
                               TRUE ~ sample_id)) %>%
  filter(!(sample_id %in% c('undetermined'))) %>%
  mutate(version = 'miseq')

# 2022
# miseq
retention_2022_miseq <- retention_2022_miseq1 %>%
  bind_rows(retention_2022_miseq2) %>%
  # clean sample name garbage
  #mutate(sample_id = str_remove_all(sample_id, 'filtered[0-9]{8}_')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{3}_L001_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{2}_L001_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{1}_L001_R1_001')) %>%
  mutate(sample_id = tolower(sample_id)) %>%
    # add a 0 for only ones with 100s
  mutate(sample_id = case_when(str_detect(sample_id, 'coe[0-9]{3}$') ~ str_replace(sample_id, 'coe', 'coe-0'),
                               str_detect(sample_id, 'coe[0-9]{4}$') ~ str_replace(sample_id, 'coe', 'coe-'),
                               str_detect(sample_id, 'exblank-2022') ~ str_replace(sample_id, 'exblank-2022-', 'exblank-2022-0'),
                               str_detect(sample_id, 'xn') ~ str_replace_all(sample_id, 'xn', 'exblank-2022-'),
                               str_detect(sample_id, 'neg-pcr') ~ str_replace_all(sample_id, 'neg-pcr', 'negpcr-2022-'),
                               str_detect(sample_id, 'peco2022-negpcr') ~ str_replace_all(sample_id, 'peco2022-negpcr', 'negpcr-2022-'),
                               TRUE ~ sample_id)) %>%
  filter(sample_id %in% missing_samples$sample_id) %>%
  mutate(version = 'miseq')

# nextseq
retention_2022_nextseq <- retention_2022 %>%
  mutate(sample_id = str_remove_all(sample_id, 'filtered')) %>%
  left_join(retention_2022_cut) %>%
  left_join(retention_2022_raw) %>%
    # clean sample name garbage
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{3}_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{2}_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{1}_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '^[0-9]{8}_')) %>%
  mutate(sample_id = tolower(sample_id)) %>%
      # add a 0 for only ones with 100s
  mutate(sample_id = case_when(str_detect(sample_id, 'coe-[0-9]{3}$') ~ str_replace(sample_id, 'coe-', 'coe-0'),
                               str_detect(sample_id, 'exblank-2022') ~ str_replace(sample_id, 'exblank-2022-', 'exblank-2022-0'),
                               str_detect(sample_id, 'xn') ~ str_replace_all(sample_id, 'xn', 'exblank-2022-'),
                               str_detect(sample_id, 'neg-pcr') ~ str_replace_all(sample_id, 'neg-pcr', 'negpcr-2022-'),
                               str_detect(sample_id, 'peco2022-negpcr') ~ str_replace_all(sample_id, 'peco2022-negpcr', 'negpcr-2022-'),
                               TRUE ~ sample_id)) %>%
  mutate(version = 'nextseq')


retention_2023_nextseq <- retention_2023 %>%
  mutate(sample_id = str_remove_all(sample_id, 'filtered')) %>%
  left_join(retention_2023_cut) %>%
  left_join(retention_2023_raw) %>%
      # clean sample name garbage
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{3}_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{2}_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{1}_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '^[0-9]{8}_')) %>%
  mutate(sample_id = tolower(sample_id)) %>%
  mutate(version = 'nextseq')


retention_2024_nextseq <- retention_2024 %>%
  mutate(sample_id = str_remove_all(sample_id, 'filtered')) %>%
  left_join(retention_2024_cut) %>%
  left_join(retention_2024_raw) %>%
      # clean sample name garbage
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{3}_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{2}_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '_S[0-9]{1}_R1_001')) %>%
  mutate(sample_id = str_remove_all(sample_id, '^[0-9]{8}_')) %>%
  mutate(sample_id = tolower(sample_id)) %>%
  mutate(version = 'nextseq')

retention_all <- retention_2021_miseq %>%
  bind_rows(retention_2022_nextseq) %>%
  bind_rows(retention_2022_miseq) %>%
  bind_rows(retention_2023_nextseq) %>%
  bind_rows(retention_2024_nextseq)
```
summary of all retention stats
```{r summary}
retention_summary <- retention_all %>%
  group_by(year, version) %>%
  summarize(n_samp = length(sample_id),
            raw = sum(raw_f) + sum(raw_r),
            after_cutadapt = sum(cutadapt_f) + sum(cutadapt_r),
            # get the rs for this on the summary
            after_filtertrim = sum(filtertrim_f) + sum(filtertrim_r),
            after_denoise = sum(denoised_f) + sum (denoised_r),
            merged = sum(merged),
            nosingletons = sum(nosingletons),
            nochimeras = sum(nochimeras)) %>%
  ungroup() %>%
  janitor::adorn_totals('row') %>%
  mutate(perc_retain = round(nochimeras / raw * 100, digits = 2),
         perc_rawmerge = round(merged / raw * 100, digits = 2),
         perc_merge_retain = round(nochimeras / merged * 100, digits = 2))

write.csv(retention_summary, here(retention_in, 'allyears', 
                                  paste0(datefield,
                                         "read_retention.csv")))

```


# variability

comparing variability in reads between next- and mi- seq

```{r samplesheets}
ss2021 <- read_csv(here('rawdata', 'peco', 'fastq', 
              '2021','SampleSheet.csv'),
              skip = 26) %>%
  janitor::clean_names() %>%
  select(sample_id) %>%
  distinct() %>%
  filter(!(sample_id %in% c("GeneratedVersion", "Sample_ID", 
                            "[Cloud_Settings]", "[Cloud_Data]"))) %>%
  mutate(year = 2021) %>%
  mutate(sample_id = tolower(sample_id)) %>%
  mutate(sample_id = str_remove_all(sample_id, '_2021$')) %>%
  mutate(sample_id = str_replace_all(sample_id, 'coe', 'coe-0')) %>%
    mutate(sample_id = case_when(str_detect(sample_id, 'negpcr') ~ 
                                 str_replace_all(sample_id, 'negpcr', 'negpcr-2021-'),
                               str_detect(sample_id, 'neg_pcr') ~ 
                                 str_replace_all(sample_id, 'neg_pcr', 'negpcr-2021-'),
                               str_detect(sample_id, 'pecoxn') ~ 
                                 str_replace_all(sample_id, 'pecoxn', 'exblank-2021-'),
                               TRUE ~ sample_id)) %>%
  mutate(version = 'miseq')

ss2023 <- read_csv(here('rawdata', 'peco', 'fastq', 
              '2023', "SampleSheet.csv"),
              skip = 27) %>%  
  janitor::clean_names() %>%
  select(sample_id) %>%
  distinct() %>%
  filter(!(sample_id %in% c("GeneratedVersion", "Sample_ID", 
                            "[Cloud_Settings]", "[Cloud_Data]")))%>%
  mutate(year = 2023) %>%
  mutate(sample_id = tolower(sample_id)) %>%
  mutate(sample_id = case_when(str_detect(sample_id, 'peco2023_redos_negpcr') ~ 
                                 str_replace_all(sample_id, 'peco2023_redos_negpcr', 'negpcr-2023-'),
                               str_detect(sample_id, 'neg-pcr-peco') ~ 
                                 str_replace_all(sample_id, 'neg-pcr-peco', 'negpcr-2023'),
                               str_detect(sample_id, 'xn') ~ 
                                 str_replace_all(sample_id, 'xn', 'exblank-2023-0'),
                               str_detect(sample_id, 'oe_8') ~ 
                                 str_replace_all(sample_id, 'oe_8', 'oe-08'),
                               str_detect(sample_id, 'oe_9') ~ 
                                 str_replace_all(sample_id, 'oe_9', 'oe-09'),
                               str_detect(sample_id, 'oe_1') ~ 
                                 str_replace_all(sample_id, 'oe_1', 'oe-1'),
                               TRUE ~ sample_id)) %>%
  mutate(version = 'nextseq')

ss2024 <- read_csv(here('rawdata', 'peco', 'fastq', 
              '2024', "SampleSheet.csv"),
              skip = 28) %>%  
  janitor::clean_names() %>%
  select(sample_id) %>%
  distinct() %>%
  filter(!(sample_id %in% c("GeneratedVersion", "Sample_ID", 
                            "[Cloud_Settings]", "[Cloud_Data]")))%>%
  mutate(year = 2024) %>%
  mutate(sample_id = tolower(sample_id)) %>%
  mutate(sample_id = str_remove_all(sample_id, '_2024$')) %>%
      mutate(sample_id = case_when(str_detect(sample_id, 'negpcr') ~ 
                                 str_replace_all(sample_id, 'negpcr', 'negpcr-2024-'),
                               str_detect(sample_id, 'neg_pcr') ~ 
                                 str_replace_all(sample_id, 'neg_pcr', 'negpcr-2024-'),
                               TRUE ~ sample_id)) %>%
  mutate(version = 'nextseq')

ss_all <- ss2021 %>%
  bind_rows(ss2023, ss2024)
  
ss_retention <- ss_all %>%
  left_join(retention_all) %>%
  mutate_all(~replace(., is.na(.), 0)) %>%
  # odd sample with higher cutadapt than raw
  filter(!(sample_id %in% c('pecoe-1013', 'pecoe-1111')))
```
## retention plots

It seems like there are a lot more 0s overall with nextseq

```{r}
ss_retention %>%
  filter(version == 'miseq') %>%
  ggplot() +
  geom_histogram(aes(x = raw_f)) +
  theme_bw()

ss_retention %>%
      filter(raw_r < 700000) %>%
  filter(version == 'nextseq') %>%
  ggplot() +
  geom_histogram(aes(x = raw_f)) +
  theme_bw()

ss_retention %>%
  filter(version == 'miseq') %>%
  ggplot() +
  geom_histogram(aes(x = cutadapt_f)) +
  theme_bw()

ss_retention %>%
      filter(raw_r < 700000) %>%
  filter(version == 'nextseq') %>%
  ggplot() +
  geom_histogram(aes(x = cutadapt_f)) +
  theme_bw()

ss_retention %>%
  filter(version == 'miseq') %>%
  ggplot() +
  geom_histogram(aes(x = dereplicated_f)) +
  theme_bw()

ss_retention %>%
      filter(raw_r < 700000) %>%
  filter(version == 'nextseq') %>%
  ggplot() +
  geom_histogram(aes(x = dereplicated_f)) +
  theme_bw()

ss_retention %>%
  filter(version == 'miseq') %>%
  ggplot() +
  geom_histogram(aes(x = nochimeras)) +
  theme_bw()

ss_retention %>%
    filter(raw_r < 700000) %>%
  filter(version == 'nextseq') %>%
  ggplot() +
  geom_histogram(aes(x = nochimeras)) +
  theme_bw()



ss_retention %>%
  select(!c(bsa_redo, percentraw_retainedby_cutadapt,
            percent_retained_aftermerge, percent_notsingleton,
            percent_notchimera, percent_retained_of_raw)) %>%
  pivot_longer(cols = !c(sample_id, year, version)) %>%
  ggplot() +
  geom_boxplot(aes(value, name)) +
  facet_wrap(~ year) +
  theme_bw()

ss_retention %>%
  filter(version == 'miseq') %>%
  select(!c(bsa_redo, percentraw_retainedby_cutadapt,
            percent_retained_aftermerge, percent_notsingleton,
            percent_notchimera, percent_retained_of_raw)) %>%
  pivot_longer(cols = !c(sample_id, year, version)) %>%
  ggplot() +
  geom_boxplot(aes(value, name)) +
  theme_bw()

ss_retention %>%
  filter(version == 'nextseq') %>%
  select(!c(bsa_redo, percentraw_retainedby_cutadapt,
            percent_retained_aftermerge, percent_notsingleton,
            percent_notchimera, percent_retained_of_raw)) %>%
  pivot_longer(cols = !c(sample_id, year, version)) %>%
  ggplot() +
  geom_boxplot(aes(value, name)) +
  theme_bw()

ss_retention %>%
  filter(version == 'nextseq') %>%
  filter(raw_r < 753071) %>%
  select(!c(bsa_redo, percentraw_retainedby_cutadapt,
            percent_retained_aftermerge, percent_notsingleton,
            percent_notchimera, percent_retained_of_raw)) %>%
  pivot_longer(cols = !c(sample_id, year, version)) %>%
  ggplot() +
  geom_boxplot(aes(value, name)) +
  theme_bw()

```



# new common names
```{r}
edna_peco <- read_csv(here('processeddata', 'peco', '2021-24_edna',
                             '20251107_peco-combined_12s_asvmatrix_fish.csv'))[-1] %>%
  select(c(found_taxa, common_name)) %>%
  distinct()

write_csv(edna_peco, here('processeddata', 'splists', '20251111_peco-commonnames.csv'))
```


