---
title: "ch2-environment"
author: "Kate Sheridan"
date: "`r Sys.Date()`"
output: html_document
---

placeholder for environment data
to add; the extractions themselves.
right now it just loads in the extractions.

```{r setup}
library(tidyverse)
library(here)

datefield = '20251113_'

# site sst
erd_data <- here('rawdata', 'temp', 'erddap')
# eDNA
dataedna <- here('processeddata', 'peco', '2021-24_edna')

```


# sst

```{r}
regions <- read_csv(here(dataedna, '20251113_peco_region-name-plotting.csv'))[-1] %>%
  rename(region_label = region_name_label) 

# load in and give headers
extracted_sst <- read_csv(here(erd_data, 'sitesstvalues', '20250713_sitesst_erddap_extract.csv'),
                          col_names = c('sst', 'filename', 'date', 'box_name', 
                                        'year', 'site_code', 'region_name', 
                                        'region_label', 'region_lat_name',
                                        'decimal_latitude', 'decimal_longitude')) %>%
  mutate(region_name = case_when(site_code == 'NC_WP' ~ 'CA_NC',
                                 TRUE ~ region_name)) %>%
  mutate(region_label = case_when(region_name == 'CA_NC' ~ 'Bodega Bay, California',
                                  region_label == 'San Fransisco Bay, California' ~ 'San Francisco Bay, California',
                                       TRUE ~ region_label)) %>%
  mutate(site_code = case_when(site_code == 'HB_SB' ~ 'HB_SR',
                               TRUE ~ site_code)) %>%
  mutate(decimal_latitude = case_when(site_code == 'HB_SR' ~ 40.77235,
                                      TRUE ~ decimal_latitude)) %>%
    mutate(decimal_longitude = case_when(site_code == 'HB_SR' ~ -124.2124,
                                      TRUE ~ decimal_longitude)) %>%
  distinct()
```

```{r}
sst_summarystats <- extracted_sst %>%
  filter(year > 2020 & year < 2025) %>%
  group_by(site_code) %>%
  summarise(sst_max = max(sst),
            sst_min = min(sst),
            sst_median = median(sst),
            sst_mean = mean(sst),
            sst_sd = sd(sst),
            peco_temp95 = quantile(sst, probs = .95),
            peco_temp90 = quantile(sst, probs = .9),
            peco_temp75 = quantile(sst, probs = .75),
            peco_temp25 = quantile(sst, probs = .25),
            peco_temp10 = quantile(sst, probs = .1),
            peco_temp05 = quantile(sst, probs = .05)
            ) %>%
  left_join(regions) %>%
  dplyr::select(!c(samples, sites, avg_region_lat))

write_csv(sst_summarystats, here(erd_data, paste0(datefield, 'sitesst_peco_summarystats.csv')))

sst_by_regionyear <- extracted_sst %>%
  select(!c(filename, date, box_name)) %>%
  distinct() %>%
  group_by(region_name, year) %>%
  mutate(sst_max = max(sst),
         sst_min = min(sst),
            sst_median = median(sst),
            sst_mean = mean(sst),
            sst_sd = sd(sst),
            region_temp95 = quantile(sst, probs = .95),
            region_temp90 = quantile(sst, probs = .9),
            region_temp75 = quantile(sst, probs = .75),
            region_temp25 = quantile(sst, probs = .25),
            region_temp10 = quantile(sst, probs = .1),
            region_temp05 = quantile(sst, probs = .05)) %>%
  ungroup() %>%
  group_by(region_name) %>%
  mutate(avg_region_lat = mean(decimal_latitude)) %>%
  ungroup() %>%
  select(!c(site_code, sst, decimal_longitude, decimal_latitude)) %>%
  distinct() %>%
  arrange(region_lat_name)

write_csv(sst_by_regionyear, here(erd_data, paste0(datefield, 'mean-summer-sst_by-region.csv')))

sst_by_siteyear <- extracted_sst %>%
  select(!c(filename, date, box_name)) %>%
  distinct() %>%
  group_by(site_code, year) %>%
  summarise(sst_max = max(sst),
            sst_min = min(sst),
            sst_median = median(sst),
            sst_mean = mean(sst),
            sst_sd = sd(sst),
            site_temp95 = quantile(sst, probs = .95),
            site_temp90 = quantile(sst, probs = .9),
            site_temp75 = quantile(sst, probs = .75),
            site_temp25 = quantile(sst, probs = .25),
            site_temp10 = quantile(sst, probs = .1),
            site_temp05 = quantile(sst, probs = .05)
            ) %>%
  ungroup() %>%
  distinct() %>% 
  left_join(regions) %>%
  select(!c(region_code, region_code_label, samples, sites)) %>%
  arrange(region_lat_name)

write_csv(sst_by_siteyear, here(erd_data, paste0(datefield, 'summer-sst-summary-stats_by-site.csv')))
```

